# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b654fed4910f29df257e40cb91471e191220ac3458e0dbfa6d294d888e281dfa9dc853567258f6972463e8e845ad94b4d637e784e0140fe66ca2bd3777571405

test:
  secret_key_base: a4befec2404800bdd690179a360b864d4fcd629c05689e4eceb9261f1b290aa2dc5bd65fcb69bb735bd00f83c5caee9603a3a3d7b05e7d993a14c8a7ae3b115b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
